package com.withplum.emojibottomsheetdialog.emoji.categoryUnicodes

enum class SmileysPeopleCategoryUnicodes(override val unicode: ByteArray) : CategoryUnicodes {
    GRINNING_FACE("\uD83D\uDE00".toByteArray(Charsets.UTF_8)),
    GRINNING_FACE_WITH_BIG_EYES("\uD83D\uDE03".toByteArray(Charsets.UTF_8)),
    GRINNING_FACE_WITH_SMILING("\uD83D\uDE04".toByteArray(Charsets.UTF_8)),
    GRINNING_SQUINTING_FACE("\uD83D\uDE06".toByteArray(Charsets.UTF_8)),
    GRINNING_FACE_WITH_SWEAT("\uD83D\uDE05".toByteArray(Charsets.UTF_8)),
    ROLLING_ON_THE_FLOOR_LAUGHING("\uD83E\uDD23".toByteArray(Charsets.UTF_8)),
    FACE_WITH_TEARS_OF_JOY("\uD83D\uDE02".toByteArray(Charsets.UTF_8)),
    SLIGHTLY_SMILING_FACE("\uD83D\uDE42".toByteArray(Charsets.UTF_8)),
    UPSIDE_DOWN_FACE("\uD83D\uDE43".toByteArray(Charsets.UTF_8)),
    WINKING_FACE("\uD83D\uDE09".toByteArray(Charsets.UTF_8)),
    SMILING_FACE_WITH_SMILING_EYES("\uD83D\uDE0A".toByteArray(Charsets.UTF_8)),
    SMILING_FACE_WITH_HALO("\uD83D\uDE04".toByteArray(Charsets.UTF_8)),
    SMILING_FACE_WITH_HEARTS("\uD83E\uDD70".toByteArray(Charsets.UTF_8)),
    SMILING_FACE_WITH_HEART_EYES("\uD83D\uDE0D".toByteArray(Charsets.UTF_8)),
    STAR_STRUCK("\uD83E\uDD29".toByteArray(Charsets.UTF_8)),
    FACE_BLOWING_A_KISS("\uD83D\uDE18".toByteArray(Charsets.UTF_8)),
    KISSING_FACE("\uD83D\uDE17".toByteArray(Charsets.UTF_8)),
    SMILING_FACE("☺️".toByteArray(Charsets.UTF_8)),
    KISSING_FACE_WITH_CLOSED_EYES("\uD83D\uDE1A".toByteArray(Charsets.UTF_8)),
    KISSING_FACE_WITH_SMILING_EYES("\uD83D\uDE19".toByteArray(Charsets.UTF_8)),
    FACE_SAVORING_FOOD("\uD83D\uDE04".toByteArray(Charsets.UTF_8)),
    FACE_WITH_TONGUE("\uD83D\uDE1B".toByteArray(Charsets.UTF_8)),
    WINKING_FACE_WITH_TONGUE("\uD83D\uDE1C".toByteArray(Charsets.UTF_8)),
    ZANY_FACE("\uD83E\uDD2A".toByteArray(Charsets.UTF_8)),
    SQUINTING_FACE_WITH_TONGUE("\uD83D\uDE1D".toByteArray(Charsets.UTF_8)),
    MONEY_MOUTH_FACE("\uD83E\uDD11".toByteArray(Charsets.UTF_8)),
    HUGGING_FACE("\uD83E\uDD17️️".toByteArray(Charsets.UTF_8)),
    FACE_WITH_HAND_OVER_MOUTH("\uD83E\uDD2D️️".toByteArray(Charsets.UTF_8)),
    SHUSHING_FACE("\uD83E\uDD2B️️".toByteArray(Charsets.UTF_8)),
    THINKING_FACE("\uD83E\uDD14️️".toByteArray(Charsets.UTF_8)),
    ZIPPER_MOUTH_FACE("\uD83E\uDD10️️".toByteArray(Charsets.UTF_8)),
    FACE_WITH_RAISED_EYEBROW("\uD83E\uDD28️".toByteArray(Charsets.UTF_8)),
    EXPRESSIONLESS_FACE("\uD83D\uDE11".toByteArray(Charsets.UTF_8)),
    WAVING_HAND("\uD83D\uDC4B".toByteArray(Charsets.UTF_8)),
    RAISED_BACK_OF_HAND("\uD83E\uDD1A".toByteArray(Charsets.UTF_8)),
    HAND_WITH_FINGERS_SPLAYED("\uD83D\uDD90️".toByteArray(Charsets.UTF_8)),
    RAISED_HAND("✋".toByteArray(Charsets.UTF_8)),
    VULCAN_SALUTE("\uD83D\uDD96".toByteArray(Charsets.UTF_8)),
    OK_HAND("\uD83D\uDC4C".toByteArray(Charsets.UTF_8)),
    PINCHING_HAND("\uD83E\uDD0F".toByteArray(Charsets.UTF_8)),
    VICTORY_HAND("✌️".toByteArray(Charsets.UTF_8)),
    CROSSED_FINGERS("\uD83E\uDD1E".toByteArray(Charsets.UTF_8)),
    LOVE_YOU_FINGERS("\uD83E\uDD1F".toByteArray(Charsets.UTF_8)),
    SIGN_OF_THE_HORNS("\uD83E\uDD18".toByteArray(Charsets.UTF_8)),
    CALL_ME_HAND("\uD83E\uDD19".toByteArray(Charsets.UTF_8)),
    BACKHAND_INDEX_POINTING_LEFT("\uD83D\uDC48".toByteArray(Charsets.UTF_8)),
    BACKHAND_INDEX_POINTING_RIGHT("\uD83D\uDC49".toByteArray(Charsets.UTF_8)),
    BACKHAND_INDEX_POINTING_UP("\uD83D\uDC46".toByteArray(Charsets.UTF_8)),
    MIDDLE_FINGER("\uD83D\uDD95".toByteArray(Charsets.UTF_8)),
    BACKHAND_INDEX_POINTING_DOWN("\uD83D\uDC47".toByteArray(Charsets.UTF_8)),
    INDEX_POINTING_UP("☝️️".toByteArray(Charsets.UTF_8)),
    THUMBS_UP("\uD83D\uDC4D".toByteArray(Charsets.UTF_8)),
    THUMBS_DOWN(" \uD83D\uDC4E".toByteArray(Charsets.UTF_8)),
    RAISED_FIST("✊".toByteArray(Charsets.UTF_8)),
    ONCOMING_FIST("\uD83D\uDC4A".toByteArray(Charsets.UTF_8)),
    LEFT_FACING_FIST("\uD83E\uDD1B".toByteArray(Charsets.UTF_8)),
    RIGHT_FACING_FIST("\uD83E\uDD1C".toByteArray(Charsets.UTF_8)),
    CLAPPING_HANDS("\uD83D\uDC4F".toByteArray(Charsets.UTF_8)),
    GRINNING_FACE_WITH_SMILING_EYES("\uD83D\uDE04".toByteArray(Charsets.UTF_8)),
    BEAMING_FACE_WITH_SMILING_EYES("\uD83D\uDE01".toByteArray(Charsets.UTF_8)),
    NEUTRAL_FACE("\uD83D\uDE10".toByteArray(Charsets.UTF_8)),
    FACE_WITHOUT_MOUTH("\uD83D\uDE36".toByteArray(Charsets.UTF_8)),
    SMIRKING_FACE("\uD83D\uDE0F".toByteArray(Charsets.UTF_8)),
    UNAMUSED_FACE("\uD83D\uDE12".toByteArray(Charsets.UTF_8)),
    FACE_WITH_ROLLING_EYES("\uD83D\uDE44".toByteArray(Charsets.UTF_8)),
    GRIMACING_FACE("\uD83D\uDE2C".toByteArray(Charsets.UTF_8)),
    LYING_FACE("\uD83E\uDD25".toByteArray(Charsets.UTF_8)),
    RELIEVED_FACE("\uD83D\uDE0C".toByteArray(Charsets.UTF_8)),
    PENSIVE_FACE("\uD83D\uDE14".toByteArray(Charsets.UTF_8)),
    SLEEPY_FACE("\uD83D\uDE2A".toByteArray(Charsets.UTF_8)),
    DROOLING_FACE("\uD83E\uDD24".toByteArray(Charsets.UTF_8)),
    SLEEPING_FACE("\uD83D\uDE34".toByteArray(Charsets.UTF_8)),
    FACE_WITH_MEDICAL_MASK("\uD83D\uDE37".toByteArray(Charsets.UTF_8)),
    FACE_WITH_THERMOMETER("\uD83E\uDD12".toByteArray(Charsets.UTF_8)),
    FACE_WITH_HEAD_BANDAGE("\uD83E\uDD15".toByteArray(Charsets.UTF_8)),
    NAUSEATED_FACE("\uD83E\uDD22".toByteArray(Charsets.UTF_8)),
    FACE_VOMITING("\uD83E\uDD2E".toByteArray(Charsets.UTF_8)),
    SNEEZING_FACE("\uD83E\uDD27".toByteArray(Charsets.UTF_8)),
    HOT_FACE("\uD83E\uDD75".toByteArray(Charsets.UTF_8)),
    COLD_FACE(" \uD83E\uDD76".toByteArray(Charsets.UTF_8)),
    WOOZY_FACE(" \uD83E\uDD74".toByteArray(Charsets.UTF_8)),
    DIZZY_FACE(" \uD83D\uDE35".toByteArray(Charsets.UTF_8)),
    EXPLODING_HEAD(" \uD83E\uDD2F".toByteArray(Charsets.UTF_8)),
    COWBOY_HAT_FACE(" \uD83E\uDD20".toByteArray(Charsets.UTF_8)),
    PARTYING_FACE(" \uD83E\uDD73".toByteArray(Charsets.UTF_8)),
    SMILING_FACE_WITH_SUNGLASSES("\uD83D\uDE0E".toByteArray(Charsets.UTF_8)),
    NERD_FACE("\uD83E\uDD13".toByteArray(Charsets.UTF_8)),
    FACE_WITH_MONOCLE("\uD83E\uDDD0".toByteArray(Charsets.UTF_8)),
    CONFUSED_FACE("\uD83D\uDE15".toByteArray(Charsets.UTF_8)),
    WORRIED_FACE("\uD83D\uDE1F".toByteArray(Charsets.UTF_8)),
    SLIGHTLY_FROWNING_FACE(" \uD83D\uDE41".toByteArray(Charsets.UTF_8)),
    FROWNING_FACE("☹".toByteArray(Charsets.UTF_8)),
    FACE_WITH_OPEN_MOUTH("\uD83D\uDE2E".toByteArray(Charsets.UTF_8)),
    HUSHED_FACE(" \uD83D\uDE2F".toByteArray(Charsets.UTF_8)),
    ASTONISHED_FACE(" \uD83D\uDE32".toByteArray(Charsets.UTF_8)),
    FLUSHED_FACE("\uD83D\uDE33".toByteArray(Charsets.UTF_8)),
    PLEADING_FACE(" \uD83E\uDD7A".toByteArray(Charsets.UTF_8)),
    FROWNING_FACE_WITH_OPEN_MOUTH(" \uD83D\uDE26".toByteArray(Charsets.UTF_8)),
    ANGUISHED_FACE(" \uD83D\uDE27".toByteArray(Charsets.UTF_8)),
    FEARFUL_FACE("\uD83D\uDE28".toByteArray(Charsets.UTF_8)),
    ANXIOUS_FACE_WITH_SWEAT(" \uD83D\uDE30".toByteArray(Charsets.UTF_8)),
    SAD_BUT_RELIEVED_FACE(" \uD83D\uDE25".toByteArray(Charsets.UTF_8)),
    CRYING_FACE(" \uD83D\uDE22".toByteArray(Charsets.UTF_8)),
    LOUDLY_CRYING_FACE(" \uD83D\uDE2D".toByteArray(Charsets.UTF_8)),
    FACE_SCREAMING_IN_FEAR(" \uD83D\uDE31".toByteArray(Charsets.UTF_8)),
    CONFOUNDED_FACE(" \uD83D\uDE16".toByteArray(Charsets.UTF_8)),
    PERSEVERING_FACE(" \uD83D\uDE23".toByteArray(Charsets.UTF_8)),
    DISAPPOINTED_FACE(" \uD83D\uDE1E ".toByteArray(Charsets.UTF_8)),
    DOWNCAST_FACE_WITH_SWEAT("\uD83D\uDE13".toByteArray(Charsets.UTF_8)),
    WEARY_FACE(" \uD83D\uDE29 ".toByteArray(Charsets.UTF_8)),
    TIRED_FACE("\uD83D\uDE2B ".toByteArray(Charsets.UTF_8)),
    YAWNING_FACE("\uD83E\uDD71".toByteArray(Charsets.UTF_8)),
    FACE_WITH_STEAM_FROM_NOSE(" \uD83D\uDE24".toByteArray(Charsets.UTF_8)),
    POUTING_FACE("\uD83D\uDE21".toByteArray(Charsets.UTF_8)),
    ANGRY_FACE(" \uD83D\uDE20".toByteArray(Charsets.UTF_8)),
    FACE_WITH_SYMBOLS_ON_MOUTH("\uD83E\uDD2C".toByteArray(Charsets.UTF_8)),
    SMILING_FACE_WITH_HORNS("\uD83D\uDE08".toByteArray(Charsets.UTF_8)),
    ANGRY_FACE_WITH_HORNS("\uD83D\uDC7F".toByteArray(Charsets.UTF_8)),
    SKULL("\uD83D\uDC80".toByteArray(Charsets.UTF_8)),
    SKULL_AND_CROSSBONES("☠".toByteArray(Charsets.UTF_8)),
    PILE_OF_POO("\uD83D\uDCA9".toByteArray(Charsets.UTF_8)),
    CLOWN_FACE("\uD83E\uDD21".toByteArray(Charsets.UTF_8)),
    OGRE("\uD83D\uDC79".toByteArray(Charsets.UTF_8)),
    GOBLIN("\uD83D\uDC7A".toByteArray(Charsets.UTF_8)),
    GHOST("\uD83D\uDC7B".toByteArray(Charsets.UTF_8)),
    ALIEN("\uD83D\uDC7D".toByteArray(Charsets.UTF_8)),
    ALIEN_MONSTER("\uD83D\uDC7E".toByteArray(Charsets.UTF_8)),
    ROBOT("\uD83E\uDD16".toByteArray(Charsets.UTF_8)),
    GRINNING_CAT("\uD83D\uDE3A".toByteArray(Charsets.UTF_8)),
    GRINNING_CAT_WITH_SMILING_EYES("\uD83D\uDE38".toByteArray(Charsets.UTF_8)),
    CAT_WITH_TEARS_OF_JOY("\uD83D\uDE39".toByteArray(Charsets.UTF_8)),
    SMILING_CAT_WITH_HEART_EYES("\uD83D\uDE3B".toByteArray(Charsets.UTF_8)),
    CAT_WITH_WRY_SMILE("\uD83D\uDE3C".toByteArray(Charsets.UTF_8)),
    KISSING_CAT("\uD83D\uDE3D".toByteArray(Charsets.UTF_8)),
    WEARY_CAT("\uD83D\uDE40".toByteArray(Charsets.UTF_8)),
    CRYING_CAT("\uD83D\uDE3F".toByteArray(Charsets.UTF_8)),
    POUTING_CAT("\uD83D\uDE3E".toByteArray(Charsets.UTF_8)),
    KISS_MARK("\uD83D\uDC8B".toByteArray(Charsets.UTF_8)),
    LOVE_YOU_GESTURE("\uD83E\uDD1F".toByteArray(Charsets.UTF_8)),
    RAISING_HANDS("\uD83D\uDE4C".toByteArray(Charsets.UTF_8)),
    OPEN_HANDS(" \uD83D\uDC50".toByteArray(Charsets.UTF_8)),
    PALMS_UP_TOGETHER(" \uD83E\uDD32".toByteArray(Charsets.UTF_8)),
    HANDSHAKE(" \uD83E\uDD1D".toByteArray(Charsets.UTF_8)),
    FOLDED_HANDS(" \uD83D\uDE4F".toByteArray(Charsets.UTF_8)),
    WRITING_HAND("✍".toByteArray(Charsets.UTF_8)),
    NAIL_POLISH(" \uD83D\uDC85".toByteArray(Charsets.UTF_8)),
    SELFIE(" \uD83E\uDD33".toByteArray(Charsets.UTF_8)),
    FLEXED_BICEPS(" \uD83D\uDCAA".toByteArray(Charsets.UTF_8)),
    MECHANICAL_ARM(" \uD83E\uDDBE ".toByteArray(Charsets.UTF_8)),
    MECHANICAL_LEG("\uD83E\uDDBF".toByteArray(Charsets.UTF_8)),
    LEG(" \uD83E\uDDB5".toByteArray(Charsets.UTF_8)),
    FOOT(" \uD83E\uDDB6".toByteArray(Charsets.UTF_8)),
    EAR(" \uD83D\uDC42".toByteArray(Charsets.UTF_8)),
    EAR_WITH_HEARING_AID(" \uD83E\uDDBB".toByteArray(Charsets.UTF_8)),
    NOSE(" \uD83D\uDC43".toByteArray(Charsets.UTF_8)),
    BRAIN(" \uD83E\uDDE0".toByteArray(Charsets.UTF_8)),
    TOOTH(" \uD83E\uDDB7".toByteArray(Charsets.UTF_8)),
    BONE(" \uD83E\uDDB4".toByteArray(Charsets.UTF_8)),
    EYES(" \uD83D\uDC40".toByteArray(Charsets.UTF_8)),
    EYE(" \uD83D\uDC41".toByteArray(Charsets.UTF_8)),
    TONGUE(" \uD83D\uDC45".toByteArray(Charsets.UTF_8)),
    MOUTH(" \uD83D\uDC44".toByteArray(Charsets.UTF_8)),
    BABY(" \uD83D\uDC76".toByteArray(Charsets.UTF_8)),
    CHILD(" \uD83E\uDDD2 ".toByteArray(Charsets.UTF_8)),
    BOY("\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    GIRL(" \uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    PERSON(" \uD83E\uDDD1".toByteArray(Charsets.UTF_8)),
    PERSON_BLOND_HAIR(" \uD83D\uDC71".toByteArray(Charsets.UTF_8)),
    MAN(" \uD83D\uDC68".toByteArray(Charsets.UTF_8)),
    MAN_BEARD("\uD83E\uDDD4".toByteArray(Charsets.UTF_8)),
    MAN_RED_HAIR("\uD83D\uDC68\u200D\uD83E\uDDB0".toByteArray(Charsets.UTF_8)),
    MAN_CURLY_HAIR("\uD83D\uDC68\u200D\uD83E\uDDB1".toByteArray(Charsets.UTF_8)),
    MAN_WHITE_HAIR("\uD83D\uDC68\u200D\uD83E\uDDB3".toByteArray(Charsets.UTF_8)),
    MAN_BALD("\uD83D\uDC68\u200D\uD83E\uDDB2".toByteArray(Charsets.UTF_8)),
    WOMAN("\uD83D\uDC69".toByteArray(Charsets.UTF_8)),
    WOMAN_RED_HAIR("\uD83D\uDC69\u200D\uD83E\uDDB0".toByteArray(Charsets.UTF_8)),
    PERSON_RED_HAIR("\uD83E\uDDD1\u200D\uD83E\uDDB0".toByteArray(Charsets.UTF_8)),
    WOMAN_CURLY_HAIR("\uD83D\uDC69\u200D\uD83E\uDDB1".toByteArray(Charsets.UTF_8)),
    PERSON_CURLY_HAIR("\uD83E\uDDD1\u200D\uD83E\uDDB1".toByteArray(Charsets.UTF_8)),
    WOMAN_WHITE_HAIR("\uD83D\uDC69\u200D\uD83E\uDDB3".toByteArray(Charsets.UTF_8)),
    PERSON_WHITE_HAIR("\uD83E\uDDD1\u200D\uD83E\uDDD1\u200D".toByteArray(Charsets.UTF_8)),
    WOMAN_BALD("\uD83D\uDC69\u200D\uD83E\uDDB2".toByteArray(Charsets.UTF_8)),
    PERSON_BALD("\uD83D\uDC69\u200D\uD83E\uDDB2\uD83E\uDDB2".toByteArray(Charsets.UTF_8)),
    WOMAN_BLOND_HAIR(" \uD83D\uDC71\u200D♀".toByteArray(Charsets.UTF_8)),
    MAN_BLOND_HAIR("\uD83D\uDC71\u200D♂".toByteArray(Charsets.UTF_8)),
    OLDER_PERSON("\uD83E\uDDD3".toByteArray(Charsets.UTF_8)),
    OLD_MAN("\uD83D\uDC74".toByteArray(Charsets.UTF_8)),
    OLD_WOMAN("\uD83D\uDC75".toByteArray(Charsets.UTF_8)),
    PERSON_FROWNING("\uD83D\uDE4D".toByteArray(Charsets.UTF_8)),
    MAN_FROWNING("\uD83D\uDE4D\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_FROWNING("\uD83D\uDE4D\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_POUTING("\uD83D\uDE4E".toByteArray(Charsets.UTF_8)),
    MAN_POUTING("\uD83D\uDE4E\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_POUTING("\uD83D\uDE4E\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_GESTURING_NO("\uD83D\uDE45".toByteArray(Charsets.UTF_8)),
    MAN_GESTURING_NO("\uD83D\uDE45\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_GESTURING_NO("\uD83D\uDE45\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_GESTURING_OK("\uD83D\uDE46".toByteArray(Charsets.UTF_8)),
    MAN_GESTURING_OK("\uD83D\uDE46\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_GESTURING_OK("\uD83D\uDE46\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_TIPPING_HAND("\uD83D\uDC81".toByteArray(Charsets.UTF_8)),
    MAN_TIPPING_HAND("\uD83D\uDC81\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_TIPPING_HAND("\uD83D\uDC81\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_RAISING_HAND("\uD83D\uDE4B".toByteArray(Charsets.UTF_8)),
    MAN_RAISING_HAND("\uD83D\uDE4B\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_RAISING_HAND("\uD83D\uDE4B\u200D♀".toByteArray(Charsets.UTF_8)),
    DEAF_PERSON("\uD83E\uDDCF".toByteArray(Charsets.UTF_8)),
    DEAF_MAN("\uD83E\uDDCF\u200D♂".toByteArray(Charsets.UTF_8)),
    DEAF_WOMAN("\uD83E\uDDCF\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_BOWING("\uD83D\uDE47".toByteArray(Charsets.UTF_8)),
    MAN_BOWING("\uD83D\uDE47\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_BOWING("\uD83D\uDE47\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_FACEPALMING("\uD83E\uDD26".toByteArray(Charsets.UTF_8)),
    MAN_FACEPALMING("\uD83E\uDD26\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_FACEPALMING("\uD83E\uDD26\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_SHRUGGING("\uD83E\uDD37".toByteArray(Charsets.UTF_8)),
    MAN_SHRUGGING("\uD83E\uDD37\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_SHRUGGING("\uD83E\uDD37\u200D♀".toByteArray(Charsets.UTF_8)),
    HEALTH_WORKER("\uD83E\uDDD1\u200D⚕".toByteArray(Charsets.UTF_8)),
    MAN_HEALTH_WORKER("\uD83D\uDC68\u200D⚕".toByteArray(Charsets.UTF_8)),
    WOMAN_HEALTH_WORKER("\uD83D\uDC69\u200D⚕".toByteArray(Charsets.UTF_8)),
    STUDENT("\uD83E\uDDD1\u200D\uD83C\uDF93".toByteArray(Charsets.UTF_8)),
    MAN_STUDENT("\uD83D\uDC68\u200D\uD83C\uDF93".toByteArray(Charsets.UTF_8)),
    WOMAN_STUDENT("\uD83D\uDC69\u200D\uD83C\uDF93".toByteArray(Charsets.UTF_8)),
    TEACHER("\uD83E\uDDD1\u200D\uD83C\uDFEB".toByteArray(Charsets.UTF_8)),
    MAN_TEACHER("\uD83D\uDC68\u200D\uD83C\uDFEB".toByteArray(Charsets.UTF_8)),
    WOMAN_TEACHER("\uD83D\uDC69\u200D\uD83C\uDFEB".toByteArray(Charsets.UTF_8)),
    JUDGE("\uD83E\uDDD1\u200D⚖️".toByteArray(Charsets.UTF_8)),
    MAN_JUDGE("\uD83D\uDC68\u200D⚖️".toByteArray(Charsets.UTF_8)),
    WOMAN_JUDGE("\uD83D\uDC69\u200D⚖️".toByteArray(Charsets.UTF_8)),
    FARMER("\uD83E\uDDD1\u200D\uD83C\uDF3E".toByteArray(Charsets.UTF_8)),
    MAN_FARMER("\uD83D\uDC68\u200D🌾".toByteArray(Charsets.UTF_8)),
    WOMAN_FARMER("\uD83D\uDC69\u200D🌾".toByteArray(Charsets.UTF_8)),
    COOK("\uD83E\uDDD1\u200D\uD83C\uDF73".toByteArray(Charsets.UTF_8)),
    MAN_COOK("\uD83D\uDC68\u200D\uD83C\uDF73".toByteArray(Charsets.UTF_8)),
    WOMAN_COOK("\uD83D\uDC69\u200D\uD83C\uDF73".toByteArray(Charsets.UTF_8)),
    MECHANIC("\uD83E\uDDD1\u200D\uD83D\uDD27".toByteArray(Charsets.UTF_8)),
    MAN_MECHANIC("\uD83D\uDC68\u200D\uD83D\uDD27".toByteArray(Charsets.UTF_8)),
    WOMAN_MECHANIC("\uD83D\uDC69\u200D\uD83D\uDD27".toByteArray(Charsets.UTF_8)),
    FACTORY_WORKER("\uD83E\uDDD1\u200D\uD83C\uDFED".toByteArray(Charsets.UTF_8)),
    MAN_FACTORY_WORKER("\uD83D\uDC68\u200D\uD83C\uDFED".toByteArray(Charsets.UTF_8)),
    WOMAN_FACTORY_WORKER("\uD83D\uDC69\u200D\uD83C\uDFED".toByteArray(Charsets.UTF_8)),
    OFFICE_WORKER("\uD83E\uDDD1\u200D\uD83D\uDCBC".toByteArray(Charsets.UTF_8)),
    MAN_OFFICE_WORKER("\uD83D\uDC68\u200D\uD83D\uDCBC".toByteArray(Charsets.UTF_8)),
    WOMAN_OFFICE_WORKER("\uD83D\uDC69\u200D\uD83D\uDCBC".toByteArray(Charsets.UTF_8)),
    SCIENTIST("\uD83E\uDDD1\u200D\uD83D\uDD2C".toByteArray(Charsets.UTF_8)),
    MAN_SCIENTIST("\uD83D\uDC68\u200D\uD83D\uDD2C".toByteArray(Charsets.UTF_8)),
    WOMAN_SCIENTIST("\uD83D\uDC69\u200D\uD83D\uDD2C".toByteArray(Charsets.UTF_8)),
    TECHNOLOGIST("\uD83E\uDDD1\u200D\uD83D\uDCBB".toByteArray(Charsets.UTF_8)),
    MAN_TECHNOLOGIST("\uD83D\uDC68\u200D\uD83D\uDCBB".toByteArray(Charsets.UTF_8)),
    WOMAN_TECHNOLOGIST("\uD83D\uDC69\u200D\uD83D\uDCBB".toByteArray(Charsets.UTF_8)),
    SINGER("\uD83E\uDDD1\u200D\uD83C\uDFA4".toByteArray(Charsets.UTF_8)),
    MAN_SINGER("\uD83D\uDC68\u200D\uD83C\uDFA4".toByteArray(Charsets.UTF_8)),
    WOMAN_SINGER("\uD83D\uDC69\u200D\uD83C\uDFA4".toByteArray(Charsets.UTF_8)),
    ARTIST("\uD83E\uDDD1\u200D\uD83C\uDFA8".toByteArray(Charsets.UTF_8)),
    MAN_ARTIST("\uD83D\uDC68\u200D\uD83C\uDFA8".toByteArray(Charsets.UTF_8)),
    WOMAN_ARTIST("\uD83D\uDC69\u200D🎨".toByteArray(Charsets.UTF_8)),
    PILOT("\uD83E\uDDD1\u200D✈️".toByteArray(Charsets.UTF_8)),
    MAN_PILOT("\uD83D\uDC68\u200D✈️".toByteArray(Charsets.UTF_8)),
    WOMAN_PILOT("\uD83D\uDC69\u200D✈️".toByteArray(Charsets.UTF_8)),
    ASTRONAUT("\uD83E\uDDD1\u200D\uD83D\uDE80".toByteArray(Charsets.UTF_8)),
    MAN_ASTRONAUT("\uD83D\uDC68\u200D\uD83D\uDE80".toByteArray(Charsets.UTF_8)),
    WOMAN_ASTRONAUT("\uD83D\uDC69\u200D\uD83D\uDE80".toByteArray(Charsets.UTF_8)),
    FIREFIGHTER("\uD83E\uDDD1\u200D\uD83D\uDE92".toByteArray(Charsets.UTF_8)),
    MAN_FIREFIGHTER("👨‍🚒".toByteArray(Charsets.UTF_8)),
    WOMAN_FIREFIGHTER("👩‍🚒".toByteArray(Charsets.UTF_8)),
    POLICE_OFFICER("👮".toByteArray(Charsets.UTF_8)),
    MAN_POLICE_OFFICER("👮‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_POLICE_OFFICER("👮‍♀".toByteArray(Charsets.UTF_8)),
    DETECTIVE("🕵".toByteArray(Charsets.UTF_8)),
    MAN_DETECTIVE("🕵️‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_DETECTIVE("🕵️‍♀".toByteArray(Charsets.UTF_8)),
    GUARD("\uD83D\uDC82".toByteArray(Charsets.UTF_8)),
    MAN_GUARD("\uD83D\uDC82\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_GUARD("\uD83D\uDC82\u200D♀".toByteArray(Charsets.UTF_8)),
    CONSTRUCTION_WORKER("\uD83D\uDC77".toByteArray(Charsets.UTF_8)),
    MAN_CONSTRUCTION_WORKER("\uD83D\uDC77\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_CONSTRUCTION_WORKER("\uD83E\uDD34♀".toByteArray(Charsets.UTF_8)),
    PRINCE("\uD83E\uDD34".toByteArray(Charsets.UTF_8)),
    PRINCESS("\uD83D\uDC78".toByteArray(Charsets.UTF_8)),
    PERSON_WEARING_TURBAN("\uD83D\uDC73".toByteArray(Charsets.UTF_8)),
    MAN_WEARING_TURBAN("\uD83D\uDC73\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_WEARING_TURBAN("\uD83D\uDC73\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_WITH_SKULLCAP("\uD83D\uDC72".toByteArray(Charsets.UTF_8)),
    WOMAN_WITH_HEADSCARF("\uD83E\uDDD5".toByteArray(Charsets.UTF_8)),
    PERSON_IN_TUXEDO("\uD83E\uDD35".toByteArray(Charsets.UTF_8)),
    PERSON_WITH_VEIL("\uD83D\uDC70".toByteArray(Charsets.UTF_8)),
    PREGNANT_WOMAN("\uD83E\uDD30".toByteArray(Charsets.UTF_8)),
    BREAST_FEEDING("\uD83E\uDD31".toByteArray(Charsets.UTF_8)),
    PERSON_FEEDING_BABY("\uD83E\uDDD1\u200D\uD83C\uDF7C".toByteArray(Charsets.UTF_8)),
    BABY_ANGEL("\uD83D\uDC7C".toByteArray(Charsets.UTF_8)),
    SANTA_CLAUS("\uD83C\uDF85".toByteArray(Charsets.UTF_8)),
    MRS_CLAUS("🤶".toByteArray(Charsets.UTF_8)),
    SUPERHERO("🦸".toByteArray(Charsets.UTF_8)),
    MAN_SUPERHERO("🦸‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_SUPERHERO("🦸‍♀".toByteArray(Charsets.UTF_8)),
    SUPERVILLAIN("🦹".toByteArray(Charsets.UTF_8)),
    MAN_SUPERVILLAIN("🦹‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_SUPERVILLAIN("🦹‍♀".toByteArray(Charsets.UTF_8)),
    MAGE("🧙".toByteArray(Charsets.UTF_8)),
    MAN_MAGE("🧙‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_MAGE("🧙‍♀".toByteArray(Charsets.UTF_8)),
    FAIRY("🧚".toByteArray(Charsets.UTF_8)),
    MAN_FAIRY("🧚‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_FAIRY("🧚‍♀".toByteArray(Charsets.UTF_8)),
    VAMPIRE("🧛".toByteArray(Charsets.UTF_8)),
    MAN_VAMPIRE("🧛‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_VAMPIRE("🧛‍♀".toByteArray(Charsets.UTF_8)),
    MERPERSON("🧜".toByteArray(Charsets.UTF_8)),
    MERMAN("🧜‍♂".toByteArray(Charsets.UTF_8)),
    MERMAID("🧜‍♀".toByteArray(Charsets.UTF_8)),
    ELF("🧝".toByteArray(Charsets.UTF_8)),
    MAN_ELF("🧝‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_ELF("🧝‍♀".toByteArray(Charsets.UTF_8)),
    GENIE("🧞".toByteArray(Charsets.UTF_8)),
    MAN_GENIE("🧞‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_GENIE("🧞‍♀".toByteArray(Charsets.UTF_8)),
    ZOMBIE("🧟".toByteArray(Charsets.UTF_8)),
    MAN_ZOMBIE("🧟‍♂".toByteArray(Charsets.UTF_8)),
    WOMAN_ZOMBIE("🧟‍♀".toByteArray(Charsets.UTF_8)),
    PERSON_GETTING_MASSAGE("\uD83D\uDC86".toByteArray(Charsets.UTF_8)),
    MAN_GETTING_MASSAGE("\uD83D\uDC86\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_GETTING_MASSAGE("\uD83D\uDC86\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_GETTING_HAIRCUT("\uD83D\uDC87".toByteArray(Charsets.UTF_8)),
    MAN_GETTING_HAIRCUT("\uD83D\uDC87\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_GETTING_HAIRCUT(" \uD83D\uDC87\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_WALKING("\uD83D\uDEB6".toByteArray(Charsets.UTF_8)),
    MAN_WALKING("\uD83D\uDEB6\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_WALKING("\uD83D\uDEB6\u200D♀️".toByteArray(Charsets.UTF_8)),
    PERSON_STANDING("\uD83E\uDDCD".toByteArray(Charsets.UTF_8)),
    MAN_STANDING("\uD83E\uDDCD\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_STANDING("\uD83E\uDDCD\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_KNEELING("\uD83E\uDDCE".toByteArray(Charsets.UTF_8)),
    MAN_KNEELING("\uD83E\uDDCE\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_KNEELING("\uD83E\uDDCE\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_WITH_WHITE_CANE("\uD83E\uDDD1\u200D\uD83E\uDDAF".toByteArray(Charsets.UTF_8)),
    MAN_WITH_WHITE_CANE("\uD83D\uDC68\u200D\uD83E\uDDAF".toByteArray(Charsets.UTF_8)),
    WOMAN_WITH_WHITE_CANE("\uD83D\uDC69\u200D\uD83E\uDDAF".toByteArray(Charsets.UTF_8)),
    PERSON_IN_MOTORIZED_WHEELCHAIR("\uD83E\uDDD1\u200D\uD83E\uDDBC".toByteArray(Charsets.UTF_8)),
    MAN_IN_MOTORIZED_WHEELCHAIR("\uD83D\uDC68\u200D\uD83E\uDDBC".toByteArray(Charsets.UTF_8)),
    WOMAN_IN_MOTORIZED_WHEELCHAIR("\uD83D\uDC69\u200D\uD83E\uDDBC".toByteArray(Charsets.UTF_8)),
    PERSON_IN_MANUAL_WHEELCHAIR("\uD83E\uDDD1\u200D\uD83E\uDDBD".toByteArray(Charsets.UTF_8)),
    MAN_IN_MANUAL_WHEELCHAIR("\uD83D\uDC68\u200D\uD83E\uDDBD".toByteArray(Charsets.UTF_8)),
    WOMAN_IN_MANUAL_WHEELCHAIR("\uD83D\uDC69\u200D\uD83E\uDDBD".toByteArray(Charsets.UTF_8)),
    PERSON_RUNNING("\uD83C\uDFC3".toByteArray(Charsets.UTF_8)),
    MAN_RUNNING("\uD83C\uDFC3\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_RUNNING("\uD83C\uDFC3\u200D♀".toByteArray(Charsets.UTF_8)),
    WOMAN_DANCING("\uD83D\uDC83".toByteArray(Charsets.UTF_8)),
    MAN_DANCING("\uD83D\uDD7A".toByteArray(Charsets.UTF_8)),
    PERSON_IN_SUIT_LEVITATING("\uD83D\uDD74".toByteArray(Charsets.UTF_8)),
    PEOPLE_WITH_BUNNY_EARS("\uD83D\uDC6F".toByteArray(Charsets.UTF_8)),
    MEN_WITH_BUNNY_EARS("\uD83D\uDC6F\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMEN_WITH_BUNNY_EARS("\uD83D\uDC6F\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_IN_STEAMY_ROOM("\uD83E\uDDD6".toByteArray(Charsets.UTF_8)),
    MAN_IN_STEAMY_ROOM("\uD83E\uDDD6\u200D♂".toByteArray(Charsets.UTF_8)),
    WOMAN_IN_STEAMY_ROOM("\uD83E\uDDD6\u200D♀".toByteArray(Charsets.UTF_8)),
    PERSON_IN_LOTUS_POSITION("\uD83E\uDDD8".toByteArray(Charsets.UTF_8)),
    PEOPLE_HOLDING_HANDS("\uD83E\uDDD1\u200D\uD83E\uDD1D\u200D🧑".toByteArray(Charsets.UTF_8)),
    WOMEN_HOLDING_HANDS("\uD83D\uDC6D".toByteArray(Charsets.UTF_8)),
    WOMAN_AND_MAN_HOLDING_HANDS("\uD83D\uDC6B".toByteArray(Charsets.UTF_8)),
    MEN_HOLDING_HANDS("\uD83D\uDC6C".toByteArray(Charsets.UTF_8)),
    KISS("\uD83D\uDC8F".toByteArray(Charsets.UTF_8)),
    KISS_MAN_MAN("\uD83D\uDC68\u200D❤️\u200D\uD83D\uDC8B\u200D\uD83D\uDC68".toByteArray(Charsets.UTF_8)),
    KISS_WOMAN_WOMAN("\uD83D\uDC69\u200D❤️\u200D\uD83D\uDC8B\u200D\uD83D\uDC69".toByteArray(Charsets.UTF_8)),
    COUPLE_WITH_HEART("\uD83D\uDC91".toByteArray(Charsets.UTF_8)),
    COUPLE_WITH_HEART_MAN_MAN("\uD83D\uDC68\u200D❤️\u200D\uD83D\uDC68".toByteArray(Charsets.UTF_8)),
    COUPLE_WITH_HEART_WOMAN_WOMAN("\uD83D\uDC69\u200D❤️\u200D\uD83D\uDC69".toByteArray(Charsets.UTF_8)),
    FAMILY("\uD83D\uDC6A".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_WOMAN_BOY("\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_WOMAN_GIRL("\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_WOMAN_GIRL_BOY("\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_WOMAN_BOY_BOY("\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC66\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_WOMAN_GIRL_GIRL("\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_MAN_BOY("\uD83D\uDC68\u200D\uD83D\uDC68\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_MAN_GIRL("\uD83D\uDC68\u200D\uD83D\uDC68\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_MAN_GIRL_BOY("\uD83D\uDC68\u200D\uD83D\uDC68\u200D\uD83D\uDC67\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_MAN_BOY_BOY("\uD83D\uDC68\u200D\uD83D\uDC68\u200D\uD83D\uDC66\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_MAN_GIRL_GIRL("\uD83D\uDC68\u200D\uD83D\uDC68\u200D\uD83D\uDC67\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_WOMAN_BOY("\uD83D\uDC69\u200D\uD83D\uDC69\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_WOMAN_GIRL("\uD83D\uDC69\u200D\uD83D\uDC69\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_WOMAN_GIRL_BOY("\uD83D\uDC69\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_WOMAN_BOY_BOY("\uD83D\uDC69\u200D\uD83D\uDC69\u200D\uD83D\uDC66\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_WOMAN_GIRL_GIRL("\uD83D\uDC69\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_BOY("\uD83D\uDC68\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_BOY_BOY("\uD83D\uDC68\u200D\uD83D\uDC66\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_GIRL("\uD83D\uDC68\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_GIRL_BOY("\uD83D\uDC68\u200D\uD83D\uDC67\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_MAN_GIRL_GIRL("\uD83D\uDC68\u200D\uD83D\uDC67\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_BOY("\uD83D\uDC69\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_BOY_BOY("\uD83D\uDC69\u200D\uD83D\uDC66\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_GIRL("\uD83D\uDC69\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_GIRL_BOY("\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC66".toByteArray(Charsets.UTF_8)),
    FAMILY_WOMAN_GIRL_GIRL("\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC67".toByteArray(Charsets.UTF_8)),
    SPEAKING_HEAD("\uD83D\uDDE3️".toByteArray(Charsets.UTF_8)),
    BUST_IN_SILHOUETTE("\uD83D\uDC64".toByteArray(Charsets.UTF_8)),
    BUSTS_IN_SILHOUETTE("\uD83D\uDC65".toByteArray(Charsets.UTF_8));
}
